import { createFileRoute } from "@tanstack/react-router";
import { CreditCard, Plus, ShieldCheck, Trash2 } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/finance/app-shell";
import { useFinance } from "@/components/finance/finance-provider";
import { brl } from "@/lib/finance-data";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { toast } from "sonner";
import type { FinanceCard } from "@/lib/finance-data";

export const Route = createFileRoute("/cartoes")({ head: () => ({ meta: [{ title: "Cartões — Manager Finance" }, { name: "description", content: "Acompanhe limites, faturas atuais e gastos futuros de todos os cartões." }, { property: "og:title", content: "Cartões — Manager Finance" }, { property: "og:description", content: "Todos os seus cartões e faturas em uma única visão." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: CardsPage });

function CardsPage() { const {cards,transactions,addCard,removeCard}=useFinance(); const [open,setOpen]=useState(false); const [pendingDelete,setPendingDelete]=useState<FinanceCard|null>(null); const [deleting,setDeleting]=useState(false); const usage=cards.map(card=>({...card,used:transactions.filter(t=>t.card_id===card.id&&t.due_date.startsWith("2026-09")).reduce((s,t)=>s+t.amount,0),future:transactions.filter(t=>t.card_id===card.id&&t.due_date>"2026-09-30").reduce((s,t)=>s+t.amount,0)})); const linkedCount=pendingDelete?transactions.filter(item=>item.card_id===pendingDelete.id).length:0; async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await addCard({name:String(f.get("name")??"").trim().slice(0,60),credit_limit:Number(f.get("limit")),closing_day:Number(f.get("closing")),due_day:Number(f.get("due")),color:String(f.get("color")??"brand")});setOpen(false)} async function confirmDelete(){if(!pendingDelete||deleting)return;setDeleting(true);try{await removeCard(pendingDelete.id);toast.success("Cartão excluído.");setPendingDelete(null)}catch(error){toast.error(error instanceof Error&&error.message==="CARD_HAS_TRANSACTIONS"?"O cartão possui lançamentos vinculados.":"Não foi possível excluir o cartão.")}finally{setDeleting(false)}} return <AppShell><div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3 sm:flex sm:flex-wrap sm:justify-between sm:gap-4"><div className="min-w-0"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Crédito</p><h1 className="mt-1 truncate font-display text-2xl font-semibold sm:text-3xl">Meus cartões</h1><p className="mt-1 text-sm text-muted-foreground">{brl.format(usage.reduce((s,c)=>s+c.used+c.future,0))} comprometidos no total</p></div><Button className="shrink-0" onClick={()=>setOpen(true)}><Plus/><span className="hidden sm:inline">Novo cartão</span><span className="sm:hidden">Novo</span></Button></div>
  <div className="mt-6 grid gap-4 lg:grid-cols-3">{usage.map((card)=><article key={card.id} className="glass-panel relative overflow-hidden rounded-[24px] p-4 sm:p-5"><div className={`absolute inset-x-0 top-0 h-1 bg-${card.color}`}/><div className="flex items-center justify-between"><span className={`grid size-11 shrink-0 place-items-center rounded-xl bg-${card.color}/15 text-${card.color}`}><CreditCard/></span><div className="flex items-center gap-2"><span className="text-xs text-muted-foreground">fecha dia {card.closing_day}</span><Button className="min-h-11 min-w-11" size="icon" variant="glass" onClick={()=>setPendingDelete(card)} title="Excluir cartão" aria-label={`Excluir cartão ${card.name}`}><Trash2/></Button></div></div><h2 className="mt-4 font-display text-xl font-semibold sm:mt-5">{card.name}</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:mt-5"><div className="min-w-0"><p className="text-xs text-muted-foreground">Fatura atual</p><strong className="break-words font-display text-sm sm:text-base">{brl.format(card.used)}</strong></div><div className="min-w-0"><p className="text-xs text-muted-foreground">Limite disponível</p><strong className="break-words font-display text-sm sm:text-base">{brl.format(Math.max(0,card.credit_limit-card.used))}</strong></div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-glass"><div className={`h-full bg-${card.color}`} style={{width:`${Math.min(100,card.used/card.credit_limit*100)}%`}}/></div><div className="mt-3 flex justify-between gap-3 text-xs text-muted-foreground"><span>Futuros {brl.format(card.future)}</span><span className="shrink-0">vence dia {card.due_day}</span></div></article>)}</div>
  <section className="glass-panel mt-4 rounded-[28px] p-5"><div className="flex items-center gap-3"><ShieldCheck className="text-success"/><div><h2 className="font-display font-semibold">Resumo de faturas</h2><p className="text-sm text-muted-foreground">Quanto está comprometido em cada cartão</p></div></div><div className="mt-5 divide-y divide-border">{usage.map(card=><div className="flex items-center justify-between py-3" key={card.id}><span className="flex items-center gap-2"><span className={`size-2.5 rounded-full bg-${card.color}`}/>{card.name}</span><strong className="font-display">{brl.format(card.used+card.future)}</strong></div>)}</div></section>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="border-glass-border bg-background/95"><DialogHeader><DialogTitle>Novo cartão</DialogTitle><DialogDescription>Informe os dados usados para calcular faturas e limites.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="Nome"><Input name="name" maxLength={60} required placeholder="Ex.: Itaú"/></Field><Field label="Limite total"><Input name="limit" type="number" min="0" step="0.01" required/></Field><div className="grid grid-cols-2 gap-3"><Field label="Dia de fechamento"><Input name="closing" type="number" min="1" max="31" required/></Field><Field label="Dia de vencimento"><Input name="due" type="number" min="1" max="31" required/></Field></div><Field label="Cor"><select name="color" className="h-9 w-full rounded-md border border-input bg-transparent px-3"><option className="bg-background" value="brand">Azul</option><option className="bg-background" value="accent">Verde</option><option className="bg-background" value="warn">Amarelo</option><option className="bg-background" value="danger">Rosa</option></select></Field><Button className="w-full">Salvar cartão</Button></form></DialogContent></Dialog><AlertDialog open={Boolean(pendingDelete)} onOpenChange={(next)=>{if(!next&&!deleting)setPendingDelete(null)}}><AlertDialogContent className="border-glass-border bg-background/95 text-foreground backdrop-blur-2xl"><AlertDialogHeader><AlertDialogTitle>{linkedCount>0?"Este cartão não pode ser excluído":`Excluir cartão ${pendingDelete?.name}?`}</AlertDialogTitle><AlertDialogDescription>{linkedCount>0?`Existem ${linkedCount} lançamentos vinculados. Exclua ou altere esses lançamentos antes de remover o cartão.`:"Esta ação não pode ser desfeita."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={deleting}>{linkedCount>0?"Entendi":"Cancelar"}</AlertDialogCancel>{linkedCount===0&&<AlertDialogAction disabled={deleting} className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={()=>void confirmDelete()}>Excluir cartão</AlertDialogAction>}</AlertDialogFooter></AlertDialogContent></AlertDialog></AppShell> }
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}