import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, ArrowDownRight, ArrowUpRight, CalendarClock, ChevronRight, Eye, EyeOff } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/finance/app-shell";
import { TransactionDialog } from "@/components/finance/transaction-dialog";
import { useFinance } from "@/components/finance/finance-provider";
import { brl, shortBrl } from "@/lib/finance-data";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Visão geral — Manager Finance" }, { name: "description", content: "Veja saldo, receitas, gastos, cartões e próximas contas em uma visão centralizada." }, { property: "og:title", content: "Visão geral — Manager Finance" }, { property: "og:description", content: "Sua situação financeira atual e futura em um só lugar." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: Dashboard,
});

function Dashboard() {
  const { cards, incomes, transactions, signedIn } = useFinance();
  const [dialog, setDialog] = useState(false);
  const [hidden, setHidden] = useState(false);
  const stats = useMemo(() => {
    const current = transactions.filter((item) => item.due_date.startsWith("2026-09") && item.transaction_type === "expense");
    const income = incomes.filter((item) => item.reference_month.startsWith("2026-09") && item.status === "received").reduce((sum, item) => sum + item.amount, 0);
    const expected = incomes.filter((item) => item.reference_month.startsWith("2026-09") && item.status === "expected").reduce((sum, item) => sum + item.amount, 0);
    const paid = current.filter((item) => item.status === "paid").reduce((sum, item) => sum + item.amount, 0);
    const credit = current.filter((item) => item.payment_method === "credit").reduce((sum, item) => sum + item.amount, 0);
    const instant = current.filter((item) => ["pix","debit","cash"].includes(item.payment_method)).reduce((sum, item) => sum + item.amount, 0);
    const future = transactions.filter((item) => item.due_date > "2026-09-30").reduce((sum, item) => sum + item.amount, 0);
    return { income, expected, paid, credit, instant, total: current.reduce((sum, item) => sum + item.amount, 0), available: income - instant, canSpend: income - instant - future, future };
  }, [incomes, transactions]);
  const show = (value: number) => hidden ? "R$ •••••" : brl.format(value);
  const cardUsage = cards.map((card) => ({ ...card, used: transactions.filter((item) => item.card_id === card.id).reduce((sum, item) => sum + item.amount, 0) }));
  const categories = ["Alimentação","Moradia","Educação","Assinaturas","Compras"].map((category) => ({ category, value: transactions.filter((item) => item.category === category && item.due_date.startsWith("2026-09")).reduce((sum,item) => sum + item.amount,0) })).filter((item) => item.value > 0);
  const upcoming = [...transactions].filter((item) => item.status === "pending").sort((a,b) => a.due_date.localeCompare(b.due_date)).slice(0,3);
  return <AppShell onNew={() => setDialog(true)}><TransactionDialog open={dialog} onOpenChange={setDialog} />
    {!signedIn && <div className="mb-4 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 rounded-2xl border border-warning/25 bg-warning/10 px-4 py-3 text-sm"><span className="min-w-0">Você está explorando uma demonstração. Entre para salvar seus próprios dados.</span><Button className="shrink-0" asChild size="sm" variant="glass"><a href="/auth">Entrar</a></Button></div>}
    <div className="grid gap-4 lg:grid-cols-[1.6fr_1fr]">
      <section className="glass-panel rounded-[24px] p-4 sm:rounded-[28px] sm:p-7"><div className="grid gap-4 sm:flex sm:flex-wrap sm:items-end sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2 text-[11px] font-medium uppercase tracking-[0.18em] text-muted-foreground">Saldo disponível agora <button className="shrink-0" aria-label={hidden ? "Mostrar valores" : "Ocultar valores"} onClick={() => setHidden(!hidden)}>{hidden ? <Eye className="size-4"/> : <EyeOff className="size-4"/>}</button></div><h1 className="mt-2 break-words font-display text-3xl font-bold leading-none sm:text-5xl">{show(stats.available)}</h1><p className="mt-2 text-sm text-muted-foreground">de {show(stats.income)} recebidos · Setembro 2026</p></div><div className="flex flex-wrap gap-2"><Pill tone="success"><ArrowUpRight/> + {shortBrl.format(stats.expected)} previstas</Pill><Pill tone="danger"><ArrowDownRight/> {shortBrl.format(stats.future)} futuros</Pill></div></div>
        <div className="mt-6 grid grid-cols-2 gap-2.5 sm:mt-7 sm:gap-3 md:grid-cols-3"><Metric label="Receitas do mês" value={show(stats.income)} note="Salário recebido" tone="success"/><Metric label="Total de gastos" value={show(stats.total)} note="Todos os meios"/><Metric label="Em cartões" value={show(stats.credit)} note={`${cards.length} cartões abertos`}/><Metric label="Débito · Pix · Dinheiro" value={show(stats.instant)} note="Pagos à vista"/><Metric label="Próx. meses" value={show(stats.future)} note="Comprometido" tone="warning"/><Metric label="Quanto posso gastar" value={show(stats.canSpend)} note="Após compromissos" featured/></div>
        <div className="mt-6 flex flex-wrap gap-2">{categories.map((item) => <span key={item.category} className="rounded-full border border-glass-border bg-glass px-3 py-1.5 text-xs text-muted-foreground">{item.category} <strong className="text-foreground">{shortBrl.format(item.value)}</strong></span>)}</div>
      </section>
      <section className="glass-panel rounded-[28px] p-5"><div className="flex items-center justify-between"><h2 className="font-display text-sm font-semibold">Cartões de crédito</h2><span className="rounded-full bg-glass px-2.5 py-1 text-xs text-muted-foreground">{cards.length}</span></div><div className="mt-5 space-y-5">{cardUsage.map((card) => <div key={card.id}><div className="flex items-center justify-between gap-3 text-sm"><span className="flex items-center gap-2 font-medium"><span className={`size-2.5 rounded-full bg-${card.color}`}/>{card.name}</span><span className="text-xs text-muted-foreground">{show(card.used)} / {shortBrl.format(card.credit_limit)}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-glass"><div className={`h-full rounded-full bg-${card.color}`} style={{ width: `${Math.min(100,(card.used/card.credit_limit)*100)}%` }}/></div></div>)}</div><div className="mt-6 flex items-center justify-between rounded-2xl border border-glass-border bg-glass px-4 py-3"><span className="text-sm text-muted-foreground">Total comprometido</span><strong className="font-display">{show(cardUsage.reduce((sum,item) => sum + item.used,0))}</strong></div></section>
    </div>
    <div className="mt-4 grid gap-4 lg:grid-cols-[1.6fr_1fr]"><section className="glass-panel rounded-[28px] p-5"><div className="flex items-center justify-between"><h2 className="font-display text-sm font-semibold">Lançamentos recentes</h2><a href="/lancamentos" className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground">Ver todos <ChevronRight className="size-4"/></a></div><div className="mt-3 divide-y divide-border">{transactions.slice(0,4).map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-3"><div className="flex min-w-0 items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-glass text-xs font-semibold">{item.category.slice(0,2).toUpperCase()}</span><div className="min-w-0"><div className="truncate text-sm font-medium">{item.description}</div><div className="truncate text-xs text-muted-foreground">{formatDate(item.due_date)} · {item.payment_source} · {item.category}</div></div></div><div className="text-right"><div className="font-display text-sm font-semibold">{show(item.amount)}</div><div className={item.status === "paid" ? "text-xs text-success" : "text-xs text-warning"}>{item.status === "paid" ? "Pago" : `Pendente${item.installment_count > 1 ? ` · ${item.installment_number}/${item.installment_count}` : ""}`}</div></div></div>)}</div></section>
      <section className="glass-panel rounded-[28px] p-5"><h2 className="font-display text-sm font-semibold">Próximas contas</h2><div className="mt-4 space-y-3">{upcoming.map((item,index) => <div key={item.id} className="flex items-center gap-3 rounded-2xl border border-glass-border bg-glass p-3"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${index===0 ? "bg-danger/15 text-danger" : "bg-warning/15 text-warning"}`}>{item.due_date.slice(8)}</span><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{item.description}</div><div className="text-xs text-muted-foreground">{formatDate(item.due_date)}</div></div><strong className="font-display text-sm">{shortBrl.format(item.amount)}</strong></div>)}</div><div className="mt-4 flex gap-2 rounded-2xl border border-warning/20 bg-warning/10 p-3 text-xs text-muted-foreground"><AlertTriangle className="size-4 shrink-0 text-warning"/><span><strong className="text-warning">Atenção:</strong> há {upcoming.length} compromissos próximos do vencimento.</span></div></section></div>
  </AppShell>;
}

function Metric({ label,value,note,tone,featured }: { label:string;value:string;note:string;tone?:string;featured?:boolean }) { return <div className={`min-w-0 rounded-2xl border p-3 sm:p-4 ${featured ? "border-primary/30 bg-gradient-to-br from-primary/25 to-accent/15" : "border-glass-border bg-glass"}`}><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 break-words font-display text-base font-semibold sm:text-xl">{value}</div><div className={`mt-1 text-xs ${tone === "success" ? "text-success" : tone === "warning" ? "text-warning" : "text-muted-foreground"}`}>{note}</div></div>; }
function Pill({ tone,children }: { tone:string;children:React.ReactNode }) { return <span className={`flex items-center gap-1 rounded-full border px-3 py-1.5 text-xs ${tone === "success" ? "border-success/30 bg-success/15 text-success" : "border-danger/30 bg-danger/15 text-danger"}`}>{children}</span>; }
function formatDate(value:string) { return new Intl.DateTimeFormat("pt-BR", { day:"2-digit", month:"2-digit" }).format(new Date(`${value}T12:00:00`)); }