import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell } from "@/components/finance/app-shell";
import { TransactionDialog } from "@/components/finance/transaction-dialog";
import { useFinance } from "@/components/finance/finance-provider";
import { brl, categories } from "@/lib/finance-data";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { toast } from "sonner";
import type { FinanceTransaction } from "@/lib/finance-data";

export const Route = createFileRoute("/lancamentos")({ head: () => ({ meta: [{ title: "Lançamentos — Manager Finance" }, { name: "description", content: "Filtre e gerencie receitas, despesas, parcelas e recorrências." }, { property: "og:title", content: "Lançamentos — Manager Finance" }, { property: "og:description", content: "Todos os seus lançamentos financeiros em um só lugar." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: TransactionsPage });

function TransactionsPage() {
  const { cards, transactions, togglePaid, removeTransaction } = useFinance(); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<FinanceTransaction|null>(null); const [query,setQuery]=useState(""); const [category,setCategory]=useState("all"); const [method,setMethod]=useState("all"); const [card,setCard]=useState("all"); const [minimumValue,setMinimumValue]=useState(""); const [maximumValue,setMaximumValue]=useState(""); const [status,setStatus]=useState("all"); const [descriptionOrder,setDescriptionOrder]=useState("default"); const [pendingDelete,setPendingDelete]=useState<FinanceTransaction|null>(null); const [deleting,setDeleting]=useState(false);
  const filtered=useMemo(() => { const minimum=parseFilterValue(minimumValue); const maximum=parseFilterValue(maximumValue); const results=transactions.filter((item) => item.description.toLowerCase().includes(query.toLowerCase()) && (category==="all"||item.category===category) && (method==="all"||item.payment_method===method) && (card==="all"||(card==="none"?!item.card_id:item.card_id===card)) && (minimum===null||item.amount>=minimum) && (maximum===null||item.amount<=maximum) && (status==="all"||item.status===status)); if(descriptionOrder==="default")return results; return [...results].sort((a,b)=>descriptionOrder==="asc"?a.description.localeCompare(b.description,"pt-BR",{sensitivity:"base"}):b.description.localeCompare(a.description,"pt-BR",{sensitivity:"base"})); },[transactions,query,category,method,card,minimumValue,maximumValue,status,descriptionOrder]);
  const isSeries = pendingDelete ? pendingDelete.installment_count > 1 || pendingDelete.recurrence !== "none" : false;
  async function confirmDelete(scope:"single"|"series") { if(!pendingDelete||deleting)return; setDeleting(true); try { await removeTransaction(pendingDelete.id,scope); toast.success(scope==="series"?"Série excluída.":"Lançamento excluído."); setPendingDelete(null); } catch { toast.error("Não foi possível excluir o lançamento."); } finally { setDeleting(false); } }
  return <AppShell onNew={() => {setEditing(null);setOpen(true)}}><TransactionDialog key={editing?.id ?? "new"} open={open} onOpenChange={(next)=>{setOpen(next);if(!next)setEditing(null)}} transaction={editing}/><div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3 sm:flex sm:flex-wrap sm:justify-between sm:gap-4"><div className="min-w-0"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Movimentações</p><h1 className="mt-1 truncate font-display text-2xl font-semibold sm:text-3xl">Lançamentos</h1><p className="mt-1 text-sm text-muted-foreground">{filtered.length} registros encontrados</p></div><Button className="shrink-0" onClick={() => {setEditing(null);setOpen(true)}}><Plus/>Adicionar</Button></div>
    <section className="glass-panel mt-6 rounded-[28px] p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="relative sm:col-span-2"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar descrição"/></div><Filter value={category} setValue={setCategory} options={["all|Todas as categorias",...categories]}/><Filter value={method} setValue={setMethod} options={["all|Todos os pagamentos","credit|Cartão","debit|Débito","pix|Pix","cash|Dinheiro"]}/><Filter value={card} setValue={setCard} options={["all|Todos os cartões","none|Sem cartão",...cards.map((item)=>`${item.id}|${item.name}`)]}/><Input value={minimumValue} onChange={(e)=>setMinimumValue(e.target.value)} inputMode="decimal" placeholder="Valor mínimo" aria-label="Valor mínimo"/><Input value={maximumValue} onChange={(e)=>setMaximumValue(e.target.value)} inputMode="decimal" placeholder="Valor máximo" aria-label="Valor máximo"/><Filter value={status} setValue={setStatus} options={["all|Todos os status","paid|Pago","pending|Pendente"]}/><Filter value={descriptionOrder} setValue={setDescriptionOrder} options={["default|Ordenação padrão","asc|Descrição: A–Z","desc|Descrição: Z–A"]}/></div></section>
    <section className="glass-panel mt-4 overflow-hidden rounded-[24px] sm:rounded-[28px]"><div className="hidden grid-cols-[1.4fr_.75fr_1.1fr_.7fr_auto] gap-4 border-b border-border px-5 py-3 text-xs text-muted-foreground md:grid"><span>Descrição</span><span>Pagamento</span><span>Datas</span><span>Valor</span><span>Ações</span></div><div className="divide-y divide-border">{filtered.map((item)=><article key={item.id} className="grid grid-cols-[minmax(0,1fr)_auto] gap-x-3 gap-y-2 px-4 py-4 md:grid-cols-[1.4fr_.75fr_1.1fr_.7fr_auto] md:items-center md:px-5"><div className="min-w-0"><div className="truncate font-medium">{item.description}</div><div className="truncate text-xs text-muted-foreground">{item.category}{item.installment_count>1 ? ` · ${item.installment_number}/${item.installment_count}`:""}{item.recurrence!=="none" ? " · Recorrente":""}</div></div><div className="text-right md:text-left"><strong className="font-display text-sm sm:text-base">{brl.format(item.amount)}</strong><div className={item.status==="paid"?"text-xs text-success":"text-xs text-warning"}>{item.status==="paid"?"Pago":"Pendente"}</div></div><div className="min-w-0 text-xs text-muted-foreground md:text-sm"><p className="truncate">{item.payment_source}</p></div><div className="text-right text-[11px] text-muted-foreground md:text-left md:text-xs"><p>Comp. {formatDate(item.issue_date)}</p><p>Venc. {formatDate(item.due_date)}</p></div><div className="col-span-2 flex gap-2 pt-1 md:col-span-1 md:gap-1 md:pt-0"><Button className="min-h-11 min-w-11 md:min-h-9 md:min-w-9" size="icon" variant="glass" onClick={()=>{setEditing(item);setOpen(true)}} title="Editar" aria-label={`Editar ${item.description}`}><Pencil/></Button><Button className="min-h-11 min-w-11 md:min-h-9 md:min-w-9" size="icon" variant="glass" onClick={()=>void togglePaid(item.id)} title="Alterar status" aria-label={`Alterar status de ${item.description}`}><CheckCircle2/></Button><Button className="min-h-11 min-w-11 md:min-h-9 md:min-w-9" size="icon" variant="glass" onClick={()=>setPendingDelete(item)} title="Excluir" aria-label={`Excluir ${item.description}`}><Trash2/></Button></div></article>)}{filtered.length===0&&<p className="px-5 py-12 text-center text-sm text-muted-foreground">Nenhum lançamento encontrado.</p>}</div></section>
    <AlertDialog open={Boolean(pendingDelete)} onOpenChange={(next)=>{if(!next&&!deleting)setPendingDelete(null)}}><AlertDialogContent className="border-glass-border bg-background/95 text-foreground backdrop-blur-2xl"><AlertDialogHeader><AlertDialogTitle>Excluir {pendingDelete?.description}?</AlertDialogTitle><AlertDialogDescription>{isSeries?"Este lançamento faz parte de uma série. Escolha se deseja apagar somente este item ou toda a série.":"Esta ação não pode ser desfeita."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={deleting}>Cancelar</AlertDialogCancel>{isSeries&&<AlertDialogAction disabled={deleting} className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={()=>void confirmDelete("series")}>Excluir série</AlertDialogAction>}<AlertDialogAction disabled={deleting} className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={()=>void confirmDelete("single")}>{isSeries?"Excluir somente este":"Excluir lançamento"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </AppShell>;
}
function Filter({value,setValue,options}:{value:string;setValue:(v:string)=>void;options:readonly string[]}) { return <select value={value} onChange={(e)=>setValue(e.target.value)} className="h-9 rounded-md border border-input bg-transparent px-3 text-sm">{options.map((option)=>{const [v,l]=option.includes("|")?option.split("|"):[option,option];return <option className="bg-background" value={v} key={v}>{l}</option>})}</select> }
function formatDate(value:string){return new Intl.DateTimeFormat("pt-BR").format(new Date(`${value}T12:00:00`))}
function parseFilterValue(value:string){const parsed=Number(value.replace(",","."));return value.trim()!==""&&Number.isFinite(parsed)&&parsed>=0?parsed:null}