import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, CalendarClock, CircleDollarSign, Plus, TrendingUp } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/finance/app-shell";
import { useFinance } from "@/components/finance/finance-provider";
import { brl, categories } from "@/lib/finance-data";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export const Route = createFileRoute("/planejamento")({ head: () => ({ meta: [{ title: "Planejamento — Manager Finance" }, { name: "description", content: "Compare o mês atual com o próximo e acompanhe compromissos futuros." }, { property: "og:title", content: "Planejamento — Manager Finance" }, { property: "og:description", content: "Planeje receitas, contas e faturas dos próximos meses." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PlanningPage });

function PlanningPage(){const {incomes,transactions,addIncome}=useFinance();const[open,setOpen]=useState(false);const month=(prefix:string)=>({income:incomes.filter(i=>i.reference_month.startsWith(prefix)).reduce((s,i)=>s+i.amount,0),paid:transactions.filter(t=>t.due_date.startsWith(prefix)&&t.status==="paid").reduce((s,t)=>s+t.amount,0),pending:transactions.filter(t=>t.due_date.startsWith(prefix)&&t.status==="pending").reduce((s,t)=>s+t.amount,0)});const current=month("2026-09"),next=month("2026-10");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await addIncome({description:String(f.get("description")??"").trim().slice(0,100),amount:Number(f.get("amount")),reference_month:`${String(f.get("month"))}-01`,received_date:null,status:String(f.get("status")??"expected")});setOpen(false)}return <AppShell><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Futuro financeiro</p><h1 className="mt-1 font-display text-3xl font-semibold">Planejamento</h1><p className="mt-1 text-sm text-muted-foreground">Compare o que entrou, saiu e já está comprometido.</p></div><Button onClick={()=>setOpen(true)}><Plus/>Adicionar receita</Button></div>
<div className="mt-6 grid gap-4 lg:grid-cols-2"><Month title="Mês atual" subtitle="Setembro 2026" data={current}/><Month title="Próximo mês" subtitle="Outubro 2026" data={next}/></div>
<div className="mt-4 grid gap-4 lg:grid-cols-[1.4fr_1fr]"><section className="glass-panel rounded-[28px] p-5"><div className="flex items-center gap-3"><TrendingUp className="text-accent"/><div><h2 className="font-display font-semibold">Compromissos por categoria</h2><p className="text-sm text-muted-foreground">Setembro e próximos meses</p></div></div><div className="mt-5 space-y-4">{categories.map(cat=>{const value=transactions.filter(t=>t.category===cat).reduce((s,t)=>s+t.amount,0);const max=Math.max(...categories.map(c=>transactions.filter(t=>t.category===c).reduce((s,t)=>s+t.amount,0)),1);return value>0&&<div key={cat}><div className="mb-1.5 flex justify-between text-sm"><span>{cat}</span><span>{brl.format(value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-glass"><div className="h-full rounded-full bg-primary" style={{width:`${value/max*100}%`}}/></div></div>})}</div></section><section className="glass-panel rounded-[28px] p-5"><div className="flex items-center gap-3"><CalendarClock className="text-warning"/><h2 className="font-display font-semibold">Alertas financeiros</h2></div><div className="mt-5 space-y-3"><Alert text={`${transactions.filter(t=>t.status==="pending").length} contas ainda estão pendentes.`}/><Alert text={`${transactions.filter(t=>t.due_date>"2026-09-30").length} parcelas já comprometem os próximos meses.`}/><Alert text={next.income-next.pending < 500 ? "A margem estimada do próximo mês está baixa." : "Sua margem futura está dentro do esperado."}/></div></section></div>
<Dialog open={open} onOpenChange={setOpen}><DialogContent className="border-glass-border bg-background/95"><DialogHeader><DialogTitle>Nova receita</DialogTitle><DialogDescription>Cadastre salário recebido, previsto ou outra entrada.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="Descrição"><Input name="description" maxLength={100} required placeholder="Ex.: Salário"/></Field><Field label="Valor"><Input name="amount" type="number" min="0.01" step="0.01" required/></Field><Field label="Mês de referência"><Input name="month" type="month" defaultValue="2026-10" required/></Field><Field label="Situação"><select name="status" className="h-9 w-full rounded-md border border-input bg-transparent px-3"><option className="bg-background" value="expected">Prevista</option><option className="bg-background" value="received">Recebida</option></select></Field><Button className="w-full">Salvar receita</Button></form></DialogContent></Dialog></AppShell>}
function Month({title,subtitle,data}:{title:string;subtitle:string;data:{income:number;paid:number;pending:number}}){const left=data.income-data.paid-data.pending;return <section className="glass-panel rounded-[28px] p-5 sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{subtitle}</p><h2 className="mt-1 font-display text-xl font-semibold">{title}</h2></div><CircleDollarSign className="text-accent"/></div><div className="mt-6 grid grid-cols-2 gap-3"><Stat label="Receitas" value={data.income}/><Stat label="Gastos realizados" value={data.paid}/><Stat label="Programado" value={data.pending}/><Stat label="Restante estimado" value={left} accent/></div></section>}
function Stat({label,value,accent}:{label:string;value:number;accent?:boolean}){return <div className={`rounded-2xl border p-4 ${accent?"border-accent/25 bg-accent/10":"border-glass-border bg-glass"}`}><p className="text-xs text-muted-foreground">{label}</p><strong className={`mt-1 block font-display text-lg ${accent?"text-accent":""}`}>{brl.format(value)}</strong></div>}
function Alert({text}:{text:string}){return <div className="flex gap-3 rounded-2xl border border-warning/20 bg-warning/10 p-3 text-sm text-muted-foreground"><AlertTriangle className="size-4 shrink-0 text-warning"/><span>{text}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}