import { createFileRoute } from "@tanstack/react-router";
import { AlertTriangle, CalendarClock, CircleDollarSign, Pencil, Plus, Trash2, TrendingUp } from "lucide-react";
import { useState } from "react";
import { AppShell } from "@/components/finance/app-shell";
import { useFinance } from "@/components/finance/finance-provider";
import { brl, categories, type FinanceIncome } from "@/lib/finance-data";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { toast } from "sonner";

export const Route = createFileRoute("/planejamento")({ head: () => ({ meta: [{ title: "Planejamento — Manager Finance" }, { name: "description", content: "Compare o mês atual com o próximo e acompanhe compromissos futuros." }, { property: "og:title", content: "Planejamento — Manager Finance" }, { property: "og:description", content: "Planeje receitas, contas e faturas dos próximos meses." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: PlanningPage });

function PlanningPage(){const {incomes,transactions,addIncome,updateIncome,removeIncome}=useFinance();const[open,setOpen]=useState(false);const[editing,setEditing]=useState<FinanceIncome|null>(null);const[pendingDelete,setPendingDelete]=useState<FinanceIncome|null>(null);const[deleting,setDeleting]=useState(false);const month=(prefix:string)=>({income:incomes.filter(i=>i.reference_month.startsWith(prefix)).reduce((s,i)=>s+i.amount,0),paid:transactions.filter(t=>t.due_date.startsWith(prefix)&&t.status==="paid").reduce((s,t)=>s+t.amount,0),pending:transactions.filter(t=>t.due_date.startsWith(prefix)&&t.status==="pending").reduce((s,t)=>s+t.amount,0)});const current=month("2026-09"),next=month("2026-10");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const status=String(f.get("status")??"expected");const value={description:String(f.get("description")??"").trim().slice(0,100),amount:Number(f.get("amount")),reference_month:`${String(f.get("month"))}-01`,received_date:status==="received"?(editing?.received_date??new Date().toISOString().slice(0,10)):null,status};try{if(editing)await updateIncome(editing.id,value);else await addIncome(value);toast.success(editing?"Receita atualizada.":"Receita adicionada.");setOpen(false);setEditing(null)}catch{toast.error("Não foi possível salvar a receita.")}}async function confirmDelete(){if(!pendingDelete||deleting)return;setDeleting(true);try{await removeIncome(pendingDelete.id);toast.success("Receita excluída.");setPendingDelete(null)}catch{toast.error("Não foi possível excluir a receita.")}finally{setDeleting(false)}}return <AppShell><div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3 sm:flex sm:flex-wrap sm:justify-between sm:gap-4"><div className="min-w-0"><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Futuro financeiro</p><h1 className="mt-1 truncate font-display text-2xl font-semibold sm:text-3xl">Planejamento</h1><p className="mt-1 text-sm text-muted-foreground">Compare o que entrou, saiu e já está comprometido.</p></div><Button className="shrink-0" onClick={()=>{setEditing(null);setOpen(true)}}><Plus/><span className="hidden sm:inline">Adicionar receita</span><span className="sm:hidden">Receita</span></Button></div>
<div className="mt-6 grid gap-4 lg:grid-cols-2"><Month title="Mês atual" subtitle="Setembro 2026" data={current}/><Month title="Próximo mês" subtitle="Outubro 2026" data={next}/></div>
<div className="mt-4 grid gap-4 lg:grid-cols-[1.4fr_1fr]"><section className="glass-panel rounded-[28px] p-5"><div className="flex items-center gap-3"><TrendingUp className="text-accent"/><div><h2 className="font-display font-semibold">Compromissos por categoria</h2><p className="text-sm text-muted-foreground">Setembro e próximos meses</p></div></div><div className="mt-5 space-y-4">{categories.map(cat=>{const value=transactions.filter(t=>t.category===cat).reduce((s,t)=>s+t.amount,0);const max=Math.max(...categories.map(c=>transactions.filter(t=>t.category===c).reduce((s,t)=>s+t.amount,0)),1);return value>0&&<div key={cat}><div className="mb-1.5 flex justify-between text-sm"><span>{cat}</span><span>{brl.format(value)}</span></div><div className="h-2 overflow-hidden rounded-full bg-glass"><div className="h-full rounded-full bg-primary" style={{width:`${value/max*100}%`}}/></div></div>})}</div></section><section className="glass-panel rounded-[28px] p-5"><div className="flex items-center gap-3"><CalendarClock className="text-warning"/><h2 className="font-display font-semibold">Alertas financeiros</h2></div><div className="mt-5 space-y-3"><Alert text={`${transactions.filter(t=>t.status==="pending").length} contas ainda estão pendentes.`}/><Alert text={`${transactions.filter(t=>t.due_date>"2026-09-30").length} parcelas já comprometem os próximos meses.`}/><Alert text={next.income-next.pending < 500 ? "A margem estimada do próximo mês está baixa." : "Sua margem futura está dentro do esperado."}/></div></section></div>
<section className="glass-panel mt-4 overflow-hidden rounded-[24px] sm:rounded-[28px]"><div className="border-b border-border px-4 py-4 sm:px-5"><h2 className="font-display font-semibold">Receitas cadastradas</h2></div><div className="divide-y divide-border">{incomes.map(income=><article key={income.id} className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3 px-4 py-4 sm:px-5"><div className="min-w-0"><p className="truncate font-medium">{income.description}</p><p className="truncate text-xs text-muted-foreground">{formatMonth(income.reference_month)} · {income.status==="received"?"Recebida":"Prevista"}</p></div><div className="text-right"><strong className="font-display text-sm sm:text-base">{brl.format(income.amount)}</strong><div className="mt-1 flex justify-end gap-2"><Button className="min-h-11 min-w-11 sm:min-h-9 sm:min-w-9" size="icon" variant="glass" onClick={()=>{setEditing(income);setOpen(true)}} title="Editar" aria-label={`Editar ${income.description}`}><Pencil/></Button><Button className="min-h-11 min-w-11 sm:min-h-9 sm:min-w-9" size="icon" variant="glass" onClick={()=>setPendingDelete(income)} title="Excluir" aria-label={`Excluir ${income.description}`}><Trash2/></Button></div></div></article>)}{incomes.length===0&&<p className="px-5 py-10 text-center text-sm text-muted-foreground">Nenhuma receita cadastrada.</p>}</div></section>
<Dialog open={open} onOpenChange={(next)=>{setOpen(next);if(!next)setEditing(null)}}><DialogContent className="border-glass-border bg-background/95"><DialogHeader><DialogTitle>{editing?"Editar receita":"Nova receita"}</DialogTitle><DialogDescription>{editing?"Atualize os dados desta receita.":"Cadastre salário recebido, previsto ou outra entrada."}</DialogDescription></DialogHeader><form key={editing?.id??"new"} onSubmit={submit} className="space-y-4"><Field label="Descrição"><Input name="description" defaultValue={editing?.description??""} maxLength={100} required placeholder="Ex.: Salário"/></Field><Field label="Valor"><Input name="amount" defaultValue={editing?.amount} type="number" min="0.01" step="0.01" required/></Field><Field label="Mês de referência"><Input name="month" type="month" defaultValue={editing?.reference_month.slice(0,7)??"2026-10"} required/></Field><Field label="Situação"><select name="status" defaultValue={editing?.status??"expected"} className="h-9 w-full rounded-md border border-input bg-transparent px-3"><option className="bg-background" value="expected">Prevista</option><option className="bg-background" value="received">Recebida</option></select></Field><Button className="w-full">{editing?"Salvar alterações":"Salvar receita"}</Button></form></DialogContent></Dialog>
<AlertDialog open={Boolean(pendingDelete)} onOpenChange={(next)=>{if(!next&&!deleting)setPendingDelete(null)}}><AlertDialogContent className="border-glass-border bg-background/95 text-foreground backdrop-blur-2xl"><AlertDialogHeader><AlertDialogTitle>Excluir {pendingDelete?.description}?</AlertDialogTitle><AlertDialogDescription>Esta receita será removida e os totais serão atualizados. Esta ação não pode ser desfeita.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={deleting}>Cancelar</AlertDialogCancel><AlertDialogAction disabled={deleting} className="bg-destructive text-destructive-foreground hover:bg-destructive/90" onClick={()=>void confirmDelete()}>Excluir receita</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></AppShell>}
function Month({title,subtitle,data}:{title:string;subtitle:string;data:{income:number;paid:number;pending:number}}){const left=data.income-data.paid-data.pending;return <section className="glass-panel rounded-[24px] p-4 sm:rounded-[28px] sm:p-6"><div className="flex items-start justify-between"><div><p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">{subtitle}</p><h2 className="mt-1 font-display text-xl font-semibold">{title}</h2></div><CircleDollarSign className="shrink-0 text-accent"/></div><div className="mt-5 grid grid-cols-2 gap-2.5 sm:mt-6 sm:gap-3"><Stat label="Receitas" value={data.income}/><Stat label="Gastos realizados" value={data.paid}/><Stat label="Programado" value={data.pending}/><Stat label="Restante estimado" value={left} accent/></div></section>}
function Stat({label,value,accent}:{label:string;value:number;accent?:boolean}){return <div className={`min-w-0 rounded-2xl border p-3 sm:p-4 ${accent?"border-accent/25 bg-accent/10":"border-glass-border bg-glass"}`}><p className="text-xs text-muted-foreground">{label}</p><strong className={`mt-1 block break-words font-display text-sm sm:text-lg ${accent?"text-accent":""}`}>{brl.format(value)}</strong></div>}
function Alert({text}:{text:string}){return <div className="flex gap-3 rounded-2xl border border-warning/20 bg-warning/10 p-3 text-sm text-muted-foreground"><AlertTriangle className="size-4 shrink-0 text-warning"/><span>{text}</span></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><Label>{label}</Label>{children}</div>}
function formatMonth(value:string){return new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(new Date(`${value.slice(0,10)}T12:00:00`))}